### PR TITLE
Added a link leading to the feedback survey

### PR DESCRIPTION
**Pull request by bluemelodia**
screen shot 2015-04-03 at 4 30 51 pm

### CODE REVIEW

**Comment by danrschlosser** [comment]
Let's change the way this works:

Before the event has happened, we should the HTML like you have it now (except that the chat icon should not be blue, it should be black.).  The "Give Feedback" text is still a link to the form.

After event has happened, put the chat icon, and "Give Feedback" text into the blue button, and move the facebook icon and text that says "View on Facebook" above, where the feedback link is now.

**Comment by bluemelodia** [comment]
screen shot 2015-04-10 at 2 27 30 pm
screen shot 2015-04-10 at 2 27 21 pm

**Comment by danrschlosser** [comment]
would you take a look at the button alignment of for the feedback button?

**Comment by bluemelodia** [comment]
screen shot 2015-04-10 at 3 03 26 pm
screen shot 2015-04-10 at 3 02 56 pm

**Comment by danrschlosser** [comment]
Great!

**Pull request merged**
