### PR TITLE
added Marketing Contact centered

### PR DESCRIPTION
**Pull request by eunicekokor**
chmmggbe8yhbyoulnmkc4s4z7serimriys3zhyxry8y  

I think it looks better centered, but can make another PR with it right justified

mfdgvuah7gypebk80uyevfj4pk7bjcj1aiycxioj0s4

### CODE REVIEW

**Comment by danrschlosser** [comment]
Do we want them to email us as opposed to fill out the firm directly?

**Comment by eunicekokor** [comment]
yeah the link goes to the form. is that misleading?

**Comment by danrschlosser** [comment]
Its an email address so it seems like it would link to an email like the
other ones

**Comment by danrschlosser** [comment]
This is in the "send us an email" section, no?

**Comment by eunicekokor** [comment]
kk added a new section below the send us an email section
y86dssw75jdngd4ibd3vdc2n9ixvregoctocmv_4e00

**Comment by danrschlosser** [comment]
Put this above the email section and you're good

**Comment by eunicekokor** [comment]
kk!

**Comment by eunicekokor** [comment]
Closed #149

**Pull request merged**
