### PR TITLE
added foundry route and html file

### PR DESCRIPTION
**Pull request by benlowkh**
@danrschlosser @RaymondXu 

Can I get this into the website before tomorrow evening?

### CODE REVIEW

**Comment by eunicekokor** [comment]
looks good to me!

**Comment by benlowkh** [comment]
does the CI check need to pass? it's something to do with the consul keys, but i haven't modified that code at all

**Comment by eunicekokor** [comment]
Nope, don't worry about that, it's a problem that's not affecting if the site is up or not. Consul expects lowercase keys.

**Comment by benlowkh** [comment]
cool thanks! can you help me merge it in? i can't because i don't have write access to the repo

**Comment by eunicekokor** [comment]
I think either @danrschlosser or @RaymondXu should check + deploy. something weird happened to me when I tried to earlier #244

**Comment by danrschlosser** [comment]
Hey @eunicekokor want to give it a shot again?

**Comment by eunicekokor** [comment]
for sure!

**Pull request merged**
