### PR TITLE
squashing issues pt. 1

### PR DESCRIPTION
**Pull request by eunicekokor**
- Removed jhil's creds (even though he's a :star2:) #230 
- Fixed spelling err #229 
- Played around with title overflow stuff for the mobile view. Changing heights doesn't do much. Easy solution is to push it up by 2em, but open to anything #221 

 mobile
image

desktop
image

### CODE REVIEW

**Comment by danrschlosser** [comment]
@eunicekokor can we push it up, but only do it in a media query?

something like

```
@media screen and (max-width: $phone-max) {
    /*styles*/
}
```

?

**Comment by eunicekokor** [comment]
I was experimenting a bit with the media query and changing `top` (or even `margin-top` or `padding`) don't seem to have any effect

**Comment by danrschlosser** [comment]
Was it a problem where it was being overruled by the other rule?

you might need something like `top: -14rem !important`.

**Comment by eunicekokor** [comment]
:+1: 
screen shot 2015-08-21 at 10 52 14 am

**Comment by danrschlosser** [comment]
Sorry to be nit picky, but could we push it up a bit further (so that
there's some space between the text and the white?

**Comment by eunicekokor** [comment]
no worries. here's 16!
screen shot 2015-08-21 at 11 07 29 am

**Pull request merged**
