### PR TITLE
Maintenance Work

### PR DESCRIPTION
**Pull request by alanhdu**
- Fix the build -- most of the tests are actually for Eventum, so I just removed them (I'll open another PR against Eventum to put them back in there)
- Update our dependencies (at the very least, we _need_ to update to pick up some security fixes)
- Do some Python 2/3 compatibility work
- Move us off nose (which is deprecated) to pytest
- Cleaned up the travis build

### CODE REVIEW

**Comment by alanhdu** [comment]
Lol... looks like the tests actually passed w/ Pypy. Do you want to make that a feature of eventum (i.e. don't `allow_failure` for Pypy)?

**Comment by alanhdu** [comment]
Gentle bump @evantarrh @eunicekokor @RaymondXu @schlosser (as the people I know who work on the website).

**Comment by RaymondXu** [comment]
lgtm

**Comment by alanhdu** [comment]
(Don't have write access, so someone else will need to merge).

**Pull request merged**
