### PR TITLE
fixes to resources, jobfair page

### PR DESCRIPTION
**Pull request by eunicekokor**
for #235 and #233

### CODE REVIEW

**Comment by eunicekokor** [comment]
@anshulkgupta review changes

screen shot 2015-09-10 at 8 59 19 pm

**Comment by danrschlosser** [comment]
The blurb says "New York's" startups, which isn't true anymore, right?

**Comment by eunicekokor** [comment]
Fixed!

**Comment by danrschlosser** [comment]
lgtm

**Pull request merged**
